name: Publish build to gh page
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
