name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
